name: "NoChat"
version: "${project.version}"
main: "me.lokka30.nochat.plugin.bukkit.NoChat"
authors: ["lokka30"]
api-version: "1.13"
website: "https://github.com/lokka30/NoChat/"

permissions:
  "nochat.bypass":
    description: "Bypass the chat limiter."
    default: false
